#!/usr/bin/env ruby

require File.expand_path('lib/cdn_helpers.rb', File.dirname(__FILE__))
require 'logger'

css_file_path = ARGV[0]
css_file = File.open(css_file_path)
public_root_path = ARGV[1]
url_prefix = ARGV[2]
logger = Logger.new(STDOUT)
logger.level = Logger::INFO

CdnHelpers::CssRewriter.rewrite_css_file(logger, css_file_path, public_root_path, url_prefix)
